const searchPages = [
  { path: '/help-v2', titleKey: 'help_v2.welcome.title', bodyKeys: ['help_v2.welcome.intro'] },
  { path: '/help-v2/owner', titleKey: 'help_v2.owner_home.title', bodyKeys: ['help_v2.owner_home.intro'] },
  { path: '/help-v2/admin', titleKey: 'help_v2.admin_home.title', bodyKeys: ['help_v2.admin_home.intro'] },
  { path: '/help-v2/student', titleKey: 'help_v2.student.home.title', bodyKeys: ['help_v2.student.home.intro'] },
  { path: '/help-v2/getting-started-owner', titleKey: 'help_v2.owner_setup.getting_started.title', bodyKeys: ['help_v2.owner_setup.getting_started.intro'] },
  { path: '/help-v2/business/create-academy', titleKey: 'help_v2.owner_setup.create.title', bodyKeys: ['help_v2.owner_setup.create.intro'] },
  { path: '/help-v2/business/academy-basics', titleKey: 'help_v2.owner_setup.basics.title', bodyKeys: ['help_v2.owner_setup.basics.intro'] },
  { path: '/help-v2/business/academy-qr', titleKey: 'help_v2.owner_setup.qr.title', bodyKeys: ['help_v2.owner_setup.qr.intro'] },
  { path: '/help-v2/business/delete-academy', titleKey: 'help_v2.owner_setup.delete.title', bodyKeys: ['help_v2.owner_setup.delete.intro'] },
  { path: '/help-v2/student/join-academy', titleKey: 'help_v2.student.join.title', bodyKeys: ['help_v2.student.join.intro'] },
  { path: '/help-v2/student/memberships', titleKey: 'help_v2.student.memberships.title', bodyKeys: ['help_v2.student.memberships.intro'] },
  { path: '/help-v2/student/booking', titleKey: 'help_v2.student.booking.title', bodyKeys: ['help_v2.student.booking.intro'] },
  { path: '/help-v2/student/system-alerts', titleKey: 'help_v2.student.alerts.title', bodyKeys: ['help_v2.student.alerts.intro'] },
  { path: '/help-v2/student/broadcast', titleKey: 'help_v2.student.broadcast.title', bodyKeys: ['help_v2.student.broadcast.intro'] },
  { path: '/help-v2/student/attendance-records', titleKey: 'help_v2.student.attendance.title', bodyKeys: ['help_v2.student.attendance.intro'] },
  { path: '/help-v2/account/sign-in', titleKey: 'help_v2.account.sign_in.title', bodyKeys: ['help_v2.account.sign_in.intro'] },
  { path: '/help-v2/account/create-account', titleKey: 'help_v2.account.create.title', bodyKeys: ['help_v2.account.create.intro'] },
  { path: '/help-v2/account/reset-password', titleKey: 'help_v2.account.reset.title', bodyKeys: ['help_v2.account.reset.intro'] },
  { path: '/help-v2/account/troubleshooting', titleKey: 'help_v2.account.troubleshooting.title', bodyKeys: ['help_v2.account.troubleshooting.intro'] },
  { path: '/help-v2/settings/change-password', titleKey: 'help_v2.settings.password.title', bodyKeys: ['help_v2.settings.password.intro'] },
  { path: '/help-v2/settings/language', titleKey: 'help_v2.settings.language.title', bodyKeys: ['help_v2.settings.language.intro'] },
  { path: '/help-v2/settings/currency', titleKey: 'help_v2.settings.currency.title', bodyKeys: ['help_v2.settings.currency.intro'] },
  { path: '/help-v2/settings/privacy-settings', titleKey: 'help_v2.settings.privacy.title', bodyKeys: ['help_v2.settings.privacy.intro'] },
  { path: '/help-v2/settings/delete-account', titleKey: 'help_v2.settings.delete.title', bodyKeys: ['help_v2.settings.delete.intro'] },
  { path: '/help-v2/settings/logout', titleKey: 'help_v2.settings.logout.title', bodyKeys: ['help_v2.settings.logout.intro'] },
  { path: '/help-v2/profile/edit-profile', titleKey: 'help_v2.profile.edit.title', bodyKeys: ['help_v2.profile.edit.intro'] },
  { path: '/help-v2/profile/child-accounts', titleKey: 'help_v2.profile.children.title', bodyKeys: ['help_v2.profile.children.intro'] },
  { path: '/help-v2/business', titleKey: 'help_v2.business.overview.title', bodyKeys: ['help_v2.business.overview.intro'] },
  { path: '/help-v2/business/compare-pages', titleKey: 'help_v2.business.compare.title', bodyKeys: ['help_v2.business.compare.intro'] },
  { path: '/help-v2/business/instructors', titleKey: 'help_v2.business.instructors.title', bodyKeys: ['help_v2.business.instructors.intro'] },
  { path: '/help-v2/business/staff-access', titleKey: 'help_v2.business.staff_access.title', bodyKeys: ['help_v2.business.staff_access.intro'] },
  { path: '/help-v2/business/analytics', titleKey: 'help_v2.business.analytics.title', bodyKeys: ['help_v2.business.analytics.intro'] },
  { path: '/help-v2/portal', titleKey: 'help_v2.portal.overview.title', bodyKeys: ['help_v2.portal.overview.intro'] },
  { path: '/help-v2/portal/register', titleKey: 'help_v2.portal.register.title', bodyKeys: ['help_v2.portal.register.intro'] },
  { path: '/help-v2/portal/members', titleKey: 'help_v2.portal.members.title', bodyKeys: ['help_v2.portal.members.intro'] },
  { path: '/help-v2/portal/ranks', titleKey: 'help_v2.portal.ranks.title', bodyKeys: ['help_v2.portal.ranks.intro'] },
  { path: '/help-v2/portal/cards', titleKey: 'help_v2.portal.cards.title', bodyKeys: ['help_v2.portal.cards.intro'] },
  { path: '/help-v2/portal/reports', titleKey: 'help_v2.portal.reports.title', bodyKeys: ['help_v2.portal.reports.intro'] },
  { path: '/help-v2/schedule', titleKey: 'help_v2.schedule.overview.title', bodyKeys: ['help_v2.schedule.overview.intro'] },
  { path: '/help-v2/schedule/create-lesson', titleKey: 'help_v2.schedule.create.title', bodyKeys: ['help_v2.schedule.create.intro'] },
  { path: '/help-v2/schedule/manage-lesson', titleKey: 'help_v2.schedule.manage.title', bodyKeys: ['help_v2.schedule.manage.intro'] },
  { path: '/help-v2/schedule/book-for-students', titleKey: 'help_v2.schedule.booking.title', bodyKeys: ['help_v2.schedule.booking.intro'] },
  { path: '/help-v2/cards', titleKey: 'help_v2.cards.overview.title', bodyKeys: ['help_v2.cards.overview.intro'] },
  { path: '/help-v2/cards/how-booking-works', titleKey: 'help_v2.cards.flow.title', bodyKeys: ['help_v2.cards.flow.intro'] },
  { path: '/help-v2/cards/create-template', titleKey: 'help_v2.cards.create_template.title', bodyKeys: ['help_v2.cards.create_template.intro'] },
  { path: '/help-v2/cards/issue-cards', titleKey: 'help_v2.cards.issue.title', bodyKeys: ['help_v2.cards.issue.intro'] },
  { path: '/help-v2/cards/edit-templates', titleKey: 'help_v2.cards.edit_template.title', bodyKeys: ['help_v2.cards.edit_template.intro'] },
  { path: '/help-v2/cards/delete-templates', titleKey: 'help_v2.cards.delete_template.title', bodyKeys: ['help_v2.cards.delete_template.intro'] },
  { path: '/help-v2/cards/delete-cards', titleKey: 'help_v2.cards.delete_card.title', bodyKeys: ['help_v2.cards.delete_card.intro'] },
  { path: '/help-v2/cards/disputes', titleKey: 'help_v2.cards.records.title', bodyKeys: ['help_v2.cards.records.intro'] },
  { path: '/help-v2/members', titleKey: 'help_v2.members.overview.title', bodyKeys: ['help_v2.members.overview.intro'] },
  { path: '/help-v2/members/quick-enrollment', titleKey: 'help_v2.members.quick.title', bodyKeys: ['help_v2.members.quick.intro'] },
  { path: '/help-v2/members/quick-enrollment-vs-applications', titleKey: 'help_v2.members.compare.title', bodyKeys: ['help_v2.members.compare.intro'] },
  { path: '/help-v2/members/applications', titleKey: 'help_v2.members.applications.title', bodyKeys: ['help_v2.members.applications.intro'] },
  { path: '/help-v2/members/reject-or-ban', titleKey: 'help_v2.members.reject.title', bodyKeys: ['help_v2.members.reject.intro'] },
  { path: '/help-v2/tools', titleKey: 'help_v2.tools.overview.title', bodyKeys: ['help_v2.tools.overview.intro'] },
  { path: '/help-v2/tools/activate', titleKey: 'help_v2.tools.activate.title', bodyKeys: ['help_v2.tools.activate.intro'] },
  { path: '/help-v2/tools/timetable', titleKey: 'help_v2.tools.timetable.title', bodyKeys: ['help_v2.tools.timetable.intro'] },
  { path: '/help-v2/tools/pause-cards', titleKey: 'help_v2.tools.pause.title', bodyKeys: ['help_v2.tools.pause.intro'] },
  { path: '/help-v2/tools/broadcast', titleKey: 'help_v2.tools.broadcast.title', bodyKeys: ['help_v2.tools.broadcast.intro'] }
]

export function getV2SearchIndex(t) {
  return searchPages.map(p => {
    const title = t(p.titleKey) || ''
    const bodies = (p.bodyKeys || []).map(k => t(k) || '')
    return {
      path: p.path,
      title,
      text: [title, ...bodies].join(' ').toLowerCase()
    }
  })
}
